# .circleci/config.yml

version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 16.4
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests
    resource_class: m4pro.medium
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          no_output_timeout: 30m
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  test:
    jobs:
      - build-and-test
