# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#


# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  before_all do
    setup_circle_ci
  end
end

lane :tests do
  run_tests(
    scheme: "PrefireExample",
    destination: "platform=iOS Simulator,name=iPhone 16,arch=arm64",
    max_concurrent_simulators: 1,
    concurrent_workers: 1,
    disable_concurrent_testing: true,
    xcargs: "-skipPackagePluginValidation"
  )
end

lane :screenshotbot_ci do
  tests
  fetch_screenshotbot
  screenshotbot_upload_all
end

private_lane :fetch_screenshotbot do
  sh("curl https://screenshotbot.io/recorder.sh | sh")
end

private_lane :screenshotbot_upload_all do
  # Upload snapshot images
  sh("~/screenshotbot/recorder \
    --channel  'PrefireExample' \
    --directory ./PrefireExampleTests/__Snapshots__") 
end
